### ISSUE TITLE
Screenshot size difference - Base64 vs local PNG URL

### ISSUE THREAD

**Issue by Benek107** [macadmins/nudge#529]
Hi,

i have noticed that when i use Base64 image (light theme) for screenshot the screenshot is much smaller compared to local PNG URL (dark theme).

+ Base64 image has bigger boarder and it makes main text box smaller so there is much less text visible to user.
<img width="570" alt="SCR-20231218-sqtk" src="https://github.com/macadmins/nudge/assets/49028033/c672edfe-362e-482e-bd4e-963fe224659b">
<img width="570" alt="SCR-20231218-sqqw" src="https://github.com/macadmins/nudge/assets/49028033/db9a2532-9023-4342-afdd-96d0b13de0bd">

**Comment by Benek107** [comment]
`iVBORw0KGgoAAAANSUhEUgAAA5AAAADaCAMAAADnuV2BAAAC/VBMVEUxLDgqJTJlYWo8N0Pf3+BKRVHo5+ktKDMyLDkcWComIy1BnP9rZ3CDgIhGQk3+/v4+OUWWu0U8bCzJx9Pb2tw1MT1+e4MjWyrvZ2RIdS/5+fqoz0pygf3k5Od3hP1FQEx9iv3S0NqFgor0aGB6iP19pDyBjf3Nzc6s00+exUdCcS6jykjL9VibwEnEw8aBpz13nzpymjlpkjZtff1oev3Ix8mUt0X09Paz2lBahjOopqyv11CmzE9kjjVMejCSoP2Qt0GtrLD1b2A2aC0vYyyZo/3a2OFwbXXr6+51cXnP+VhVgTLQztXza2Ken/zW1dhoZG2LskApXyve3ODMytbT0tS7ur+enKGHrz9gijSDkf2Qs0OEqz5RfjKNnP1ulzjh3+axr7Tw7/LV1N6Zv0WMrkGepfyemvt5dn6jqfu23VWgxk18nzq/vsHQlriKbuX2dl+23k85NEBgd/3Hkr/G8VVCPUheWmNpavqnl/i0sre/5lWjoafB61S641KUk5lVUVs+gc+amJ74gV/H7ltaVl/B6FuQjZQEVCO+jsg6XI664ljpYk+Hl/2ecM10b/rVkquHqT/Fw89iXmf5e1+pk+eBce+TcNy/vcmzgsjjWUg/jOSwkd22tbnShaGKh47IibM1QV5NSFOwt/mIhY05VH9uanOylfGpfNDYnLLwX10yM0XHf6ajlvG6ktW4trypdMGMlf09esOyd7e9eq84ZyadedmUmP2osPl4aO6KYjt3mTiNipG8hby4XT8/Zy2iXDkyWiz+bl50XDM9b683Sm9QS1ZAmPnOW0M8aKQzOlFwlDZLaDHgbF1BmfxAlPPAxrZdWy+9luXjf4g/l/bUob7ejp1GWi1TT1m+bFPUZlL6i2HzbVVbaTe8v+3qbnKgbklwbD8VVyjLzejghK+br3XL2qivw4eyvaWUqUi+23fM63ulwmlujleHoVbl0NGMnnCJdmnYuM3tq52jeHR8lUWRgvDsioPAenh7mHeXtShfg0aYdKZfhmtWdFGkal4BAAApxElEQVR42uzXMWrFMBREUQcRcCXUvFp7dKH1p0n4KUzAJoaBf84eLsNsH0AMQUIQQUIQQUIQQUIQQUIQQUIQQUIQQUIQQUIQQUIQQUIQQUIQQUIQQUIQQUIQQUIQQUIQQUIQQUIQQUIQQUIQQUIQQUKQP4OsMV/6uU/gWz83X0bdDrL6XONMexkN+DF+FzHOrNnrXpCtj6P2GzZ4C/sNdYze7gTZZqsN+GfVZrseZM1m6uABe5t1Oci+7CM8ola/GmTNYwMeccy6GOQwkPCUWutikHN4kPCQfUxB8sXO/bumEYYBHH9oXw+HpjroDaLmKKKbSyLCLcEh/liSgNWAQ8ldweCQRaEhJaAIIh06ZS6CFrOldKpD5/4BTplc8h/0L+jz3r16uZ4tpqC59J7PkJj3DjlDvjx3J5G4BQVJiItQkIS4CAVJiItQkIS4iD/4koIkxC0oSEJc5OFBvqQgCREoSEL+ZxQkIS5CQRLiIv7nFCQhrkFBEuIiFCQhLvIPQdIHeBAi/G9BNntyW8scSno2EMjq0mFaa8s9+kQC4lmPGOTtlsYCSzFt6xYI8aBHCjI8zkmBv5JyY/qoEOI5jxLkM00P/CaCfl/TtWdAiKdsPshgn93vMKsXpRjLv0V5FotJRT17r0zWDwIh3rHpIH2X2UWM2aKUv5tN9mqJaHQH7e7uxGt7k9nbWNGKMnvpA0K8YrNBbquR+WTUpfysXlMSiUQ8Ho8iI0nUarV2Pk7upMWkjKjbQIg3bDLIZldMR6PG0WhUV6KKkaTV5C7XQtH9u5guksx26Z0Q4g3+574HBun71yALMXHVWDyZTQ7q9cZkNPoWjyuKsixJFG3k5+eusQIQ4gEbC3K7ymvkF4752YGh3sAkG0mjSGRPsmV6c8eT5FFW6byVeMCmgiwV5zmOTpFZJCbJh2TCmaTVZG2eZLEEmxPsvShdDe0v9N2zQicMTnyd3jIlTynIZi4Q4fST2Sl3cOoYkrYkbWPyI08SBXJN2IwjjRlSg+CiOjXFUDm9BYJjnZAnEqSvwnuK6NLs4uIUiSatIZlIJBX0pyT3T/QIV/HBBoS7bCHVAUMvxebUJnDOdbrxRJ5GkOfFCMKz1esLTkRpG5K1uGJP0n4xGZ2ZQ7J4DuunsntCPwB1QsySA8GxTsgTCHLMW+Lj8Ro5khRDck9RklaSzvs7e+aQzI5h3UqMK39SK4w7C88bTX+WuyG+6R0IjnVCXB+kLK4ep9PpNbI3eW9Ifk0kkYKWJhkXV5IyrKrTbrflcOE486WNqRxdps+6R+JFj/u5TPVYfrnY83367Fj+YWwzOtSCfC/GlXCRr1XDfM8yPpJBWLo+7Gvp9Pt2B7jPeAzD4Ssto31/DmDbvvIxEi9Ze5B9cbp6czNF9ibtQ3I/qVhJOm+57orT1j6sSMZGMseMq/jwO7dlJFFlpsq5WQ0zhXh7VwylgsANjDYB/Ax1zX1VVX0BwrL1EhMGgA7xwXf8glJDsG9f+RiJh6w7yLbRo/T6hps6mrQNyckbRak5p+RiTE4ko8j2ykFaDplwDhBOsbnQrbWfaKHL0JX45Zzh43ITIGXkGga7ZevjsvVkRpCWnGP7asdI/xrqJWsOcmD2+PPDBxGkrUjHkGx8VZJWko5brnsxPYIGDwmyHLL9vQ8ACgxlcimGXomRyFLGjxU/5BhqAifqHAJcms+gyj0/WJas90LiybgX8yBFhNuO7SseI/GOX+zdXUhTYRjA8Zd12ibYiHBl4SxaOOjCmxLBm8iybbCVNGqwCzEvbF6sZIVWCIoiFWwlaEWRFRaWUpQUZVFRBuFFu4q+ln1fRxdBEVH0PO95jueczlKxNmjn/RdU59B2gv143vOhZReknzzu3n2QkzwJHTlyfjIiSSLxWbpGThLKSLJOFumfOci1cXuYf9S7WccmeQF6OhAItNkZw/G3D9bUdKJYKI/GGEpgVJQGViuJAUvt6sAybCeh8whUP4GM2h9uoxfS75/pMYrMU1ZB9lbKHnfshg5CJBK6dOnSXopINhLJmgiRzHTJNclFVvbOGGQLY0sl6DZpien3lzO2D0lwTB6PZznzcBFULw0yVgvyqKJCRhm3c4D9kzLj/M9tygt5DftneIwi8zQbkGyGzfUtqaxsAI+QQpKmJJFsktu4UUtylJPMeDLJZ2Rl5RLf3BmC9DAI0QzSNZoYgzrmVW2t2CJB5cy+ia6PUjEtAb882KCB2xUSFepllGF7nJaY9DcHmPLiTjwGv2H/9McoQJqt7IF0BsAjzMehoaFMJMmkgrJxo5ZksgxJQgaSa6woMuCcCUhafBbRmDsnf9jjYWmycuagIai0DWkpr94uQQ+ZXMfCtoCEdTLKsN0hD0KoVYK6AST9GWn5DfunPUYB0nRlD2RVJXr8NMTboZrUkcS2g0TZZE2NQrJxBElGMpxMwrVWqGr2IMO0xJQ/7C10CqnUKUuR2ypBmn+v3W8UQtvVF4syqFaCnv8G0rB/2mMUIE1X1kB60Y3v09enT4eGnjwhkwpJ1SQXCXGUjY1AEuKXd+r+QBLuR0Le2YK0o43+2jlsnrxkxUug7Qzq9vv9cVlKeZxh8+jSy0O4ydjmZNhlvPjCKMN2e5EyQJfLJ4d6kIb90x+jAGm2sgVyKQ6yhk/Vw+7gm8ePn4LJJzumIEkmQSREJJvWRDhJSHt9p/QDirQunSXIhxJUC1Ntq/xhjyGluYzNRwRR5kRDEmfWW0QDrXbyfv18D38NyrgdX7NogLEWfDGP/TeQhv3TH6MAabayBbIfPbq+VgeDbvfwcDGh5CQxIAlpSd7AwCSApDH5J5Jl9Q3w4v2zBDlf4tPHso2Wg8v5r/MWbqXHURfSvcWqCgmrcAKfkAStjQ4u92jOIY3b6S9XnD4NynHuGkDq909/jGLJarqyBNKLHq2fq6EgxlFyk4YxSSS3A0kMPapjcpRI6laujVYU6Z0VSJxSugsm8cv6h2ns/ZKmUDedWFI04SjDdicSomJzjCD1+6c6RnFRx6RlB6QzxE8gmxEkkSwu1prcrb3Aox2SIyM3bqwhk0gSp2QkCSa1l1z5aWTIOTuQhUX6D/ucmERdbmFQvEqCdE+SOtuNXyKZeXt8knP5fGYAqd8/5TEKkCYtOyD3ywvWZkgmSSaL0WSPZkxiaFIdkiPQjTU8bhJI1ulIgsmyehS5f/qvo4opGHrp048L3dZYCNakt3H/Vga1hMENwGgn4XY/Ed3U6WBUbQUJrQJHVMbtczr5ixWFlyoPu9YyqALB6ffP/BhFJiorIFt8lQ2wYO1rxvRjEk3imFRJHscucJPbkeQIxkGSyVG4LxlJ6kiOWhsaKn0tbJbFHXPtuoE+0N2h+2cN1Ea93u647u90+L0WVERl3k4v9jDODBn2T3uM4v/9M2FZARkGj75QV1/fH0gOv3lMZ5PylESRFy5cv379y5cbEJqsk0HCL0iyqS4JaUh+8IHIMBOJ8qxsgFwKWmBAdnUBSTJJIrUke0CkliSKPHZs55cvZSMySQrnZFNTTZKHJBEkfOEHmBdfvSvKt7IBshOxfOrC9CS5R/hJK1cg2QMkzwBJEgkkd+48erS0bKSORFI1TTX0uxEoGSn7YIU36WQiUX6VBZBxtOL6/LKLIpKaZatCEhauQ0TyznEiiSJvHj6MJuuSFOKsIZG4iIVGXTiF5zCRKK/KAsjl8oB8+VIlaVy3qiR7emSRdzQijx4+vOdwaYSTpPCskkTy80o+IsUX74ryrCyADIBH19cTiQnVZB9kFIkk38CjrpzkmTtAEq/t4InkUZlkSRmQjFBIUvEInXXBmWqAiUR51b8H2YoDMpQ4AZFJ/bqVP03nDrpJJJEEkWfUIclFAsk9JcuSskj+pDknqdwN2YAjUnwLKFF+9c9B2toafD7X57GxsUQCSJJJIqmK5CnrVhTZw0Xe0S1bkeQqIIk3O+AHoASO6BF77fL5GtpsTCTKo/45SLuEIH++e5sGkxOqSZ1INxUM0rpVIalfthLJFZGI/M0D4LspJxWRjU31AFISN89FedU/B2nx+XzW8gMHDhQ8uvWiGU0m0GRzF5hURVa7KbotaRySqkhOEjjylkUIJF7WgbeyMJEoj/rXIG1hUOL6VlBQ8B5Q3n/3ItVHi9eJiT5cuMoi3WrKkOQiIVWkjuSyFaUY/L88dUTyrAveKizWrKbL9p+XW5ABUFK/EkCSyc2v3qb6+mSTgLIZpySdRlLB4PRDEkmiSG4ySYtWCUZkQIA0Wba5lui8/7eFfstcWw5BDgASq6dADUwuUk1ylNVI0q2NhqRRpJZkyYrSEl5pUp6RH1zwXgNMZKJsDn/UP1j4HzcI/wCHLVcgbVFcsXYSRtVkAZlElFylft0adNOQ7IG0y1YgqYpcXaKI5Fdb+XVWX1SMSBNl644WWv77CqPdtlyBbEOQPwp+7z3NybEJMgkoh93VmYbkKRR5DUhe0Q3JPdgq/o3ngOQyFDlaD28mbnyYKFu315IXeUFkbkBW+KxWaZ0BJK1d371tpqXrJMqxMZqRyhPnPadOneIkrwLJQ+qQ3COTpFYk4RGBDVarr0KANE02x6AlTxp02HIC0llvtbo8BX9Ivu6KYxI5jp8YHx8HlW63bFJ5cEcVeRVEAsmd+Lz5TSK5Gr5bMorEJ10/uKzWeicTmSRbrSVvKswJSNtzF4BcC/amMPnobQruhKRBpFJiGOdkMQ9FIsmLF69dA5HqkLyJcZLYqtUlkbrX+G7PxYg0Sw5LHuXICUgvzqz2RQVT9B4v8dydAJLE8S40ni4eGwuCxxRe21FEyiQPqSR5SJKbLDuL89grQJokW4clj+qw5QLkOZfLVf9t3br1YHLKMfnsVnoiQRqhe/fu3k27kWQqlUrAkESRNCSR5DEgqZpEkXtA5BoJ3u6cAGmSbK2W3NRWHsv+tdzWnIAMgxDp48qVCxasW7956jG56MHdRGJc5gggsRepsWAKRaZoSCokD8kkIYXkLiS5IgRvJ57VMUu2XkuGNoU8FqX+UJHf8veVW63eP+7cEiqKWqiqUGihZZb15gTkWhAS+r548UoITS6aaky+f3YvnVY53rr14Na9dBBJptMp7ZBEkqrJmzuR5C4kiSDXCpC/2Lvf0DbKOA7g5/W3WwdJqXpJLRKKgXE6MVsLN/SgpWHSEFpI3HHJhhs2TCFgw7Av2lECKYUSXwnSF+qLGiij+EKoIL7pgrUMipAKDkFXYbAOQQYKG0wQ9YW/3/P8Ln1S27Wzm2GYr9jcc39yJfDp7/kTdv+TPKHvFMMwVUn5Rw0SB2Ujad6eMoyo/m/zxH8BMkMgzw8MdGMIpTTZtWuZXF3+8uu6RxR59eryBnZbf8R8xyJ5JMkkCaUIFslLl1KjkUjmPiA7J8br2+MTE52amoVEcLFH229CExO8dSgRng1tOzi9OK3smk2G55R78WWBcL5+Us/1Ccy41srjCNKIPyYgDx9+GoeQqfOYAURJkXWyq2sXlEjyKo0glwVHyrVrRBJBbvz+/U87krzIuXTpjoUg7V1BhkrK05DpwTWmerAIGLOs7S+zNj+lbs0W1+XVz9AxaVecDV4vAGWmAe1aHChmUSDUQSaWbf2rQI8jSCP6eIDEr5aPjo5arwxj6ihl31WgPEIucWM7SQmSPV774YerG898s7HxpST5KfdbmSTn4nsXL97541u83chuINcantAfBIxy1AGZqraPtF92+VnK0x6AS/6Cmp8JG2SsDnFbj+D5zy7nTKaAY6/xc7OY5ITWykMGma5Uknqy5BSraZ0TnnGyUXGAD4ezjqCUqBSdclLnBMrYSiggL2edbGUHkKnANpDRGadYXhS3qshdwcplXbaDOqcJFfI5Ann27CsYBSWRJJMikiSh5CaSvFbnKECurl7d+ObHjS+/2vhYKZJIElMX+cGdP25LkDuLzJuggDxkNoKcQxqBtmQK3EPanumZB8qkdBwdDyVdGNEU6vNr7Qs5gAo1pwCw7k3HAOa2us6INJPvWAhn8FWCzE9P6yULIKy18pBBRg0jFxduzLB0ZhsUu4wHxOEpC5sO2owb8ghSwpSBGpD1QYZThtAXbgQZcQ1jSQXpnzhaxG3PMOjd0hGu1q4RaSLIIQLZ19/ff5ZUcqlUTCJKjqrzFpJEjcwRs3qLSG7cvHnzHpH8lEkqJi/+dfuP2wLk0C4gLTCjGQZJTFxHBRkHCMgHp+6j05oEKIQFyPYUFPlh59c1zjykQlRFR6BAJRTPbacRqglZzU/JfwhsGxKcFCCnqdlhQlxr5eGD9GMmeDeHQYo4ygEvQKxG/aYEmTCVd1FAmlXcV1ZAJk2DMyP2Vam2ypaeN4xYk0HavW+80UcolUopSZJJzjaat26tbmmkHHm3a3kDRS4vc7+1oUp+8l70ffR4f5D2tLZEIJlUOaqCtCFDLyELcvsBWQrNCUmHbDvB7ze3BdISrzEoyCOz8pPtDGmcdg9SXIgnAUoMkmLhL9jKowBZKAeLLtY+7LXGCWIl6oACMleOLupBYhkUB7BfupjCYpgNl2wGGbAQ6ky4hCXPSjeAJHSQqIMMeOLCcsEwIhW9THM+8qYFfJ0xjGzzQMox5IleJkkm/UqpmNwpXbe6VusahVGagt24SWshWCV/Ukh+9Mln0d+O3r79/ljv/bqsgTatDnLCAzukggy5PHh0wN5HlxUpSpB+sgAdynPvwlJiFF/K4IXCxaWZhDLNOg1YVzkTPeNbIOdoDNvKIwAZ07lKYXfTRHbUrG6BLOuUim0LLDk6gSRBXidfBFKcLlY1k+g63AgygHZjdZBVupBvn9EDEcOSPVdjFB1n8FdqOkghEv+n9JFMwZJMHpMm1ZxmolgyhUYqnf58zzqWyM3NG5t3f0eTFPzO+ed/3f21duW33/CddwfJ8UEWSZMKck08q1z4gZC2d7aBnHWpwHI6CwCFqQyA1yP6wrYNFGtB85PmOSB1Rzafv+y4YHdqrTx8kJFFnaWV9ATWL54U9UF6ekOCBEmP+7UsLEE6dDElS51PFSReEaGTGaTDF/KdsMIG9CQWZ3HQxNObCDKGQlJHMcfph5RJIpmkXyYVlErQpJjoURYqj2wKkevriPLuvXv37t7d/HN4+Gw/vtnZvt4TNt7uw71BTgJkNQKpipjzy9vaA4Ps8GS/lLMAFN5FGs15x0KRPRonD6BTWQ5GKQF1lnVRa+URgLRku0QCq4IbN3lSR+ekg1knt+SJM2L1QjgqQBbQVI7i8QUKSEIYyQuQ6oUeXVikDvAM7osYDg0h55sJct7FQd3JwcHXzpw7LjxKjixSkBxAkmhyp6DJI2pobLmyubx548aN9S/8HOseGDg//Ep/H9Zga3TUndoTZCgGXuc/QOo+SL+SzcS3xencGWRnrKHizZoArkU/yPgIQGoa7xlXzknKaydAZEmCjMUsarWehvAoQC7pfq2zyUacFzEYJLd5WpVCIE2qbCIWuaJ2PfZ2kGmLRpYEUr2wQO0wvX8Ga6VtjNDNy80E6QwhyLfrHmt9td4TlF5RKhHnWb9Mck7xq9gkk12KRxSJY8v1zU0ESVlZWcHzUCSCpAxfwLs5e4EkiUn5oha1PM9/1h+N7sH2LOwIcjxDEzP1hDxwgyEtFDYhhZ8NHkyK3coE6iztowsLhQJApj6GDKUt2mjlACBpGSKgc1I+yAK1xFaMGHIz2wgStWDAs2WFTCFDpdBR27NEDCvXCBKTxzLqCJB8If9BCNJCh6UD3qmI+5ew99zMLwaUhlx36BcEefzoWG+td+z4uTNsE0UiSTKJKGk0Sam7VFie5uLI65TYjX31hgqSRHZ3D2CZPP8n3a3EHncDSTSgXK1WM/hSbqtP6pS3T+qUs9vTthPIUA6g2K4USF45IfBzYrh6iO89onEmgJdAxLqJwyApemsh8oAgqT5d5s0E+loU4lJ1cY6+aBhugL00grQRYpIKqQCZ8d8oHRHCMqRLiQKS3zviIUi+kH+XSFrXESH+EahQd7VkIs6mgTysHQ4SkZ+xQB7trZ04N3hykGSKkWSNp11FsE4OdMscU/6TRl/tYo0YOdtzekWIXOEKiSBR4/nh4V/pbsG9QI6Dkuv1ZY8YoWrz9rMQqIJsdwCc9sZFygR3gwlX1YdrQ0Hz44HZUedbUUAuULFt5SAg7a1RWhbpybpohH2BZaxgXCKLhgqS4fGBjPgpC2HZoP3ULsrz8vnAP0HyImbUL7wS9ogcqlpCJmqkvwjNrJCBC67r/nzm3Fht7PWXXnrytXPo8Upvbw37qv19tTe4TpJL6rrKdG/LsVOnWaOMmIld3wnkHQR5Ib0XyPapjIgHkFnq0dpne0RlhKScZK0+GMgsQLzxW6o+0KyY1pnkZpoLpz9SnRKfW48NoCsgq61pnYOCnDEEMN7KMcjUIgtMyv1WPE6AGkGCLG1BECArvBySBwIpJ2urdFpGUaWATLgMMsoXJkw5+5MweN0lRxvhpoJcuDA05H57fGxs8Nln3xwkjyeu9Nb6+2snjp47Q71XnH2lISWiRJLD5/0MKBEkMayRs0IeGaQv8uehoaELC3uB5PhjyCK406JSefmFqAlmzwOBLANKDlCwY9oxP4+q0VhubmEOiXskMQ5QnO7Jm+pX50J4jp1cmw1byFlqraTTgXwOAFrrHgcByd+L83IzcZscJhmkYU5N2QxUjxsypgKS52DMXHY+YiBIWfIisVwG/G/qZKhddDxs5htBylQlSD4xN2/ywqVu4f4snwB6U0FqzyFI6+j7L7z8/ItYH1HmFZzYGTsz+KTQOUYYZdAkkVSzhbP7KTLI4RnYUwLkqbpIJDnvDg09pz0gyBE5bJsBCm0/CMg2qKdE++jySQ9kUrrohXKzYf70ug0cu0eC5JhJrZUDgdTTCInjoSM5huQddlqnOIQsEo9uAxnl78q5EuSiJ5tgSpBpW/lGXANIzhSBVH8DCMvbycqsB5B6prkgn1iionXyxXdefvaFk28Jj7XjT77w5iAWR/JI3ddan8zf7N3Na9NgHAdw0zkiomJEC1JEKoQmhlgVFsJSoUNQBoUZ1G2SiowmMLp6WC+FFTqQdTv01O3iZQxkePXkqYK3XXbx6D+g28F59+b39zxPt9SJDJXspfkWWa0vxbEPv5cnZi+IZG8ETNr5wCDXKEIr2I/vkUuIEFkAyHfSH0BOoR6F+sYx+rA2lhmkWXDpMhk68EqlybrMKv6QyNruIeaFYTL4dGRQrHCmGLzev7k6Mcb8LV1huoXgd6/iHeu/goSHKXgjcePEiItbJ1zXVvkLoJFcS54Txx7JvQ40mQGZa3PJa3wMnX7JECfHxWr07RQTe6tnt/N477KCc3CfZE+mTu/9xtClB4A6f7gg5fkSRG7NNuyU77VVeFT93IzCjkEqFXYOsnmncxvpXjLwrDfCJUjCXddiN/ff379PJEWR3CH88zIHefCcESuZi7Vas3rqH4IqmxHPrr/hSxtBcqX2m0Z4sLYyGH/3vP8PkkjeWFqaX2eIBEhMcqPdVczE8DBvOUfCtU6YGp1+FL5damh/I/Y5+PUD5NHodPLcEfz/kPLbNJR8bdRtQ0GB7FSClGOw+qgSx81K0fUQ18U8WVQrNEuGE76C4Gr4VESckaBEhkT+wFulHwLkYWUOpxlxogpAHiQCZCjjKFjTMDPBOskjkwhAQuR1Apmp1x0DHauatTRb08WydbNTtHxTyRPGLKLSj9t37t67K/ICDwpTKQ5GbvbmEjjuitwmkNfh8bCSiVekUUZaSRwg+0Em+fn/abb7PDJZiQakNF5CH7nY0HQvaLeVFIZJkw+TnaKZ08HRZRxVVa3QikdlJO9xkN0wlCC570yEquTuHHm1gHcalw4R5NBYvCKNMHLzb0Ai87DIMnWEbn1ek6MB+YH3rCnFCwLLsFu2gWESIFVF07DcIY5ivdPpdDBI0rV1GCeZxju7IZREsnsggh3OVc6TFclLlB0qkB+k+KZz/RJ5I3GgPBwZWf/llYm5oVurE+cTRygb0YCUm6hblzMNdKyBp2stNky2szgIcRwUSPJIZ5MdtehimqSfokTC5F5U/gEmiSQ/Dek9pcQsSSCHAbLQlGOQ/RL5YuIE5WIkICFyuVR6UGoZvEBimNQt9K6B7tia4VuwiVWP6vm6rvuKolhWPu9NZsGvi1Ll4SaJpDgMed4NI4mgYy2VlmOPfRS5ljgxQccaDUhpKQ2RX/UgCBTDXlx0TND0TK1cxnbHA8hK1sppKXDM510MlIibd4tqByYJZYWDpCGTkQzdCYQHJNml6T/gMb0Ud6x9FHkgcWIyEBVI+XMBIDMzQZuD1ADSU3J2q5zDdgfF0jVshzxyjkWeSTSvbM9DFpFilm9+iKS448BuxJUDqwBZ+BxXyD6KLJ2Y7391QYoIJD5pqyiRpa12F6TieZauNerlnO+hbFopG80r1q00QNJxiEoQIbE4iYAmHuwZnrN5M3x/npDJHbxJejUukH0VWRpMnIgM4gs3MpCjT2BliCrkjAOQlmf5Oae1WDbQsRLSho0CaXluUET76iqmaSoW5sjKbTXLiiUP72aJLF/wCJQIh7mNAvlkNAbZX5GlajNx7NOs4us2MpDymWUqkd8YyBYDaabsxYWybqFWzmjllo11q0Xj5KSfchwtZRiGDqIuHY4wlORRBCZZ5wqTAiV3yQrk8pm4Y+2zyJI0sHGsdzu1jQEJHiMDiU/ZDSqRnwikBpAeQObKAGlymvWWg3Urda++07DBUddNHxtXH4XSpckRJAVIrH0QTlLcBQRhLrdLKJA34gLZd5FB8uyxDjjKpyIFObCcTqNEegBZBsgAIG0G0mKvtDQUSDA1ZhuzDnkkjnmKgidW/teA5D6T31Ef08sDMcg+jHzsg39EZCBFiYTIIfBDZbSxZDVzTn2hBZAmDZN1DbXQomESBZJ7BENxAAKVPeEmBUlhEvkEj3GB7N/Ix/iBRA2y+roAkVsK+StbbY+GyYW6aeEFepICSEXXyvWWjQJpUn0MXM9iHWvRJZSCpY8HIsqkuN0AmfwCj4XX1RhknJ/s3M+LEmEcx/GJiMQnghC9eNogGtGpWwyNhzoF4qHAtqAuQUFoHQwqaNKaMA/rKbsIEmFkFw8Le62jJnrQPXjoH+gHW0SX7n2+33lscvql1W6Zzzta23InOrz4Ps8z0/5vbQJIiLwYAsj0OwMr1KzhbiZL5RwUJk38IglmWMXaWLxKjzjryeezpoUH0c8ePH3iDIlkjxybZJLS5L79ABm6qDyq/rs2B+TOVVq0roOdnk3i3iNtHUs5TEoCWYrCGn7HLgGkcR7s4qZdKOZNy7JMK24cOnGCSOJNKIaH7KRJIgmTIPmGFqyrmgKp+u/aDJAQeb3Ki1YI1JM4XAXEcil5hveQpYSOARknopVoDCCNaL5gk0c9Sul6Mh7zB5TemOQFa/W68qj6/9ockDuDt9xFK0QmDQnRkq8pk1asBNJOwmMsivlYKLoe41R0ojj/5meTmJ68YL0VVPcgVf9fmwGSz3WW5UmrkcvhdJVvdxxyb4SkKsb5GIFMlAESszJvX7Xz5DHu0vuWSiYJkyDJJ6zL6kRH9T+2SSB3brvLi9Y3mIp0pppLWtlKzgWZKBl7GCR2k4YRS1rFQsnOw6MchSTSM6lTEiWTfM0L1rvbtnxAdnrtFU2lmmwuQGJEBvdWM2lsI3E7Yw+NSCxWdYJpYhOZPOSCTOjnjRxWrKWSbUqQMe4zR8tL19kkPKYz1cfBnw7Ivqj3PEx10dSmr40v9bcihHA0lWqiOQFJJ603Q2kMyZcXzhzCYwAk0jL2kMtywjxkMMiUCZA6QCYK5tgjfmJfGWORuoVMmcW7zHcYj+nQTVxe+0kNIYZhTeYIMct0WxNtzd9Q1Fcamko12byAxBN0q2ORZ86wSD2Hj3oWdyINCdKOGXEGWXJBRs2ibRfNKMMkjybKyx/I2kiTx1U8MzcNSNH8PC1/GyQu0dFUKn9zApJEPqq5Iu9dkCKTBj5AYlknkOQwGpO/yEcRdpNXqUIR9hBz/CJzYz95rD2awiNAekvMngcy0A9oXq2+fA1/D2Q//PlyLW18CfX9jlVe8wGStpHXa6FMZikNkbRuxXmrQSKtbDkLlybWrqlsPGoRyIStwyOOWxMMEtnFYt4fPGYyodp12kBOARI1NCo8HINsrg3FcI0H58rIadaFII29uhg4K1+BrI86bXxlvYO3DLtCjEbtLy6hUrnNCUgSuYtEYkYelEOSQUJkNskuS6mSrpsEMlUw8SsMyAQlTTLJYr6I6CW/kWaPu6byCJBddoWaYugwyCZgDuRSdkWMuvgMXB3B9fwgsWsU1KChtboDvHbXvEsokSrZ3ICEyGOuyNcH74EkidzjirSSSWwmceOjYmWLBDKRt7B/dD16KIt20WtjiT0eg8cpQXbEqOUe6fQYZGMgnEag4YAYgRTDZitM+rrNcL8NY36QQNpqrXT5E7lk9S6hDnhUsr8MMjCLyCckMr305qAkuQcisV4lkBaJLGezFQKZKuSLNgZk6kuStHK1bai00SvX4xP2OB3IQB0M2VKfQfZEnVC16qLHINlUeACJjHDND9L9nbZwxiAnL6FS/ekCmwmSRd6vVUnk5feXDvJWUopMSpHligSZsOERIFO+ISkrv8Ltx0y1dp89TgkS6OokCrAYpCMV9UCM/4zqgCsFan6QzJnfOAbpXULdk1Rx8wSSRb5YhsjMUublpTFJ3khKkZVKFixJJPAxSJDkHyxyTPLtyaUMPC6/YI9Tg2wNREdrjfCBQY5EU+4pR3DGpOj1cy0/yA6/2wM5eQmVSpsvkCxyx42qu2x9zyTPuCRzORaZJZA2RDK/BIOUKKVIVOLxGKre2MEepwfJ61BMuMCPQTpUXTgKpGrW5gwki7xyqhaiIbn/5VNvSnokzWyFjncSnkdpckzyLe520Pbx1BX2OAvIjhi0eCPpX7J6IDui6/sX+UGqJavq+80ZSBa5M1Jzh+T6eyLJxztskklaJg3JQqEkRfpIvpXjsRbZyR5nAqnVBQ5RIcl/qOOBbMnj1X6zMwVI36FOQJMfKfW4gOrfB8nfSjN4+1wtFArxuvXp00v7vPMdIqkTSZyxIh9JyRFfWjt3O8jfznI2kGAngEuC7AzEWl/rr4lBR4KkHLrtoTWwZP0pSN8lwk6X726O6uHxi0r1r4PkIRl+WKu6JNc/gOSlffe8patrEg8A2EA5MSbBcYk4VmsPwzweZwaJEx2wYpCS50A+tSNB8rQTA7xt2PgpSN8lOoKv4ci/Qj3tqpoLkCwyePvwmOSBlx/J5EFp8rwR80wWaUxKlNg7pl2Oh28HZ/UIQSMNtcGJia0wLqcruk5T80CifptIrsHjD0D2CaTvEuH6gGl3663xi0r174MkkdhJHntAJPnx1jeuyX2eSfm/O2hOssm3r06OOT44ht0jefwThflpcX/9fuCXLhF2PwbcF7WJVM0HSDkkwxeZJI/JpfWX79kkDcoThDKWG5vc2JAamePFMMaj+gY6qkVoq0BCpCR5DiQ5POKaXn/z8sP7S7R6PXvhxBGYTL7beLWe5ofkXI7nXI7Ko2oh2jqQct0a1I7fXGaTclKi/QfWuQP76bM0MEqNyzePa+CoxqNqUZod5G4C+VskgzsiRz2T7FImP5Uaj0Z2BBVH1UK1pSA9ktueRw6v1iZQTmCsrR6OPN+mOKoWrcD23VsKEiTZJNp+PXLqxuoyWFJgiEBxefXGqcj17UHSqPaOqgVry0EySTbJ5K7d3RV5dufm4aM3bhw9fPPOs8iuu9foj1ij4qhatLYepGcSKL/TNqVRtZj9JZBsklVSExLJotKoWtD+GkiJ0p/CqFro/iZILwXxE3t3jNpADIRhNIsIbCXUTK07bqHzR7AhxIUNMl4Y7Pfu8PEjEAykCfJfh5Lksz0RZPOFGk6ChHcmSEhEkJCIICGRvQkS0hAkJLIeZBck/BIkvDNBQiKChET21gUJWQgSEhEkJCJISGQ9yDbcXIOLxBiLQUY/voBLHD2WgpyqiYRrxKjbapDRi1ckXGAvPRaDnEovNhJeLmZa22qQU6ntiH2dYeVD7E+IY8we14OcovbRbhVgSbs1eo1tPchTjH6qd30Df+pd/TRmjo+DBNIQJCQiSEhEkJCIICERQUIigoREBAmJCJKf9ulYAAAAAGCQv/U0dpRDjAgJI0LCiJAwIiSMCAkjQsKIkDAiJIwICSNCwoiQMCIkjAgJI0LCiJAwIiSMCAkjAdNu2Iy2ftcsAAAAAElFTkSuQmCC`

**Comment by Benek107** [comment]
![SCR-20231218-slkq_v3](https://github.com/macadmins/nudge/assets/49028033/dcea9b10-b32b-4530-9869-580fe76aa0fe)

**Comment by erikng** [comment]
Fixed with https://github.com/macadmins/nudge/releases/tag/v1.1.13.81510

**Comment by Soteyy** [comment]
We are still experiencing this issue on version 1.1.14.81549.

We would much rather prefer the usage of remote images as mentioned [here](https://github.com/macadmins/nudge/issues/444), as even with base64 we need to configure and push the updated .json file to the user machines before we can trigger Nudge on the user machines. This can be a time critical process especially for RSR releases.
